CREATE TABLE USUARIO (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(50),
    SOBRENOME VARCHAR(50),
    EMAIL VARCHAR(100),
    CELULAR VARCHAR(50),
    GENERO VARCHAR(50),
    SENHA VARCHAR(300)
);

CREATE TABLE DISCIPLINAS (
    NOME VARCHAR(50),
    ID PRIMARY KEY
);

CREATE TABLE CONTEUDOS (
    NOME VARCHAR(100),
    ID INTEGER PRIMARY KEY,
    COD_DISCIPLINA INTEGER,
    FK_DISCIPLINAS_ID INTEGER
);

CREATE TABLE PLANEJAMENTO (
    NOME VARCHAR(50),
    DT_INICIO DATE,
    DT_FIM DATE,
    FK_USUARIO_ID INTEGER,
    ID SERIAL PRIMARY KEY
);

CREATE TABLE DIA_SEMANA (
    ID INTEGER PRIMARY KEY,
    NOME VARCHAR(100)
);

CREATE TABLE PLAN_DISC (
    FK_DISCIPLINAS_ID INTEGER,
    FAZER INTEGER,
    ID INTEGER PRIMARY KEY
);

CREATE TABLE PLAN_DIA (
    FK_DIA_SEMANA_ID INTEGER,
    QTD_HORAS INTEGER,
    ID INTEGER PRIMARY KEY
);